// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'entities/kanji_progress_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8531882730285561322),
    name: 'KanjiProgressEntity',
    lastPropertyId: const obx_int.IdUid(9, 1878898559340768358),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5509583467822917161),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7815779949099553063),
        name: 'literal',
        type: 9,
        flags: 2080, // UNIQUE (32) | INDEX_HASH (2048) — corrected from 32768
        indexId: const obx_int.IdUid(1, 8740161065519850981),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1258291604801282811),
        name: 'levelId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9193240982782383782),
        name: 'statusIndex',
        type: 5,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3682829127985961573),
        name: 'hitCount',
        type: 5,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4401675952067156490),
        name: 'timesSeen',
        type: 5,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8303490706592156499),
        name: 'timesCorrect',
        type: 5,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8814723744510305798),
        name: 'timesWrong',
        type: 5,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1878898559340768358),
        name: 'lastSeenMs',
        type: 6,
        flags: 2,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 8531882730285561322),
    lastIndexId: const obx_int.IdUid(1, 8740161065519850981),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    KanjiProgressEntity: obx_int.EntityDefinition<KanjiProgressEntity>(
      model: _entities[0],
      toOneRelations: (KanjiProgressEntity object) => [],
      toManyRelations: (KanjiProgressEntity object) => {},
      getId: (KanjiProgressEntity object) => object.id,
      setId: (KanjiProgressEntity object, int id) {
        object.id = id;
      },
      objectToFB: (KanjiProgressEntity object, fb.Builder fbb) {
        final literalOffset = fbb.writeString(object.literal);
        final levelIdOffset = fbb.writeString(object.levelId);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, literalOffset);
        fbb.addOffset(2, levelIdOffset);
        fbb.addInt32(3, object.statusIndex);
        fbb.addInt32(4, object.hitCount);
        fbb.addInt32(5, object.timesSeen);
        fbb.addInt32(6, object.timesCorrect);
        fbb.addInt32(7, object.timesWrong);
        fbb.addInt64(8, object.lastSeenMs ?? 0);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final object = KanjiProgressEntity(
          id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
          literal:
              const fb.StringReader().vTableGet(buffer, rootOffset, 6, ''),
          levelId:
              const fb.StringReader().vTableGet(buffer, rootOffset, 8, ''),
          statusIndex:
              const fb.Int32Reader().vTableGet(buffer, rootOffset, 10, 0),
          hitCount:
              const fb.Int32Reader().vTableGet(buffer, rootOffset, 12, 0),
          timesSeen:
              const fb.Int32Reader().vTableGet(buffer, rootOffset, 14, 0),
          timesCorrect:
              const fb.Int32Reader().vTableGet(buffer, rootOffset, 16, 0),
          timesWrong:
              const fb.Int32Reader().vTableGet(buffer, rootOffset, 18, 0),
          lastSeenMs:
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 20),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [KanjiProgressEntity] entity fields to define ObjectBox queries.
class KanjiProgressEntity_ {
  /// See [KanjiProgressEntity.id].
  static final id = obx.QueryIntegerProperty<KanjiProgressEntity>(
      _entities[0].properties[0]);

  /// See [KanjiProgressEntity.literal].
  static final literal = obx.QueryStringProperty<KanjiProgressEntity>(
      _entities[0].properties[1]);

  /// See [KanjiProgressEntity.levelId].
  static final levelId = obx.QueryStringProperty<KanjiProgressEntity>(
      _entities[0].properties[2]);

  /// See [KanjiProgressEntity.statusIndex].
  static final statusIndex = obx.QueryIntegerProperty<KanjiProgressEntity>(
      _entities[0].properties[3]);

  /// See [KanjiProgressEntity.hitCount].
  static final hitCount = obx.QueryIntegerProperty<KanjiProgressEntity>(
      _entities[0].properties[4]);

  /// See [KanjiProgressEntity.timesSeen].
  static final timesSeen = obx.QueryIntegerProperty<KanjiProgressEntity>(
      _entities[0].properties[5]);

  /// See [KanjiProgressEntity.timesCorrect].
  static final timesCorrect = obx.QueryIntegerProperty<KanjiProgressEntity>(
      _entities[0].properties[6]);

  /// See [KanjiProgressEntity.timesWrong].
  static final timesWrong = obx.QueryIntegerProperty<KanjiProgressEntity>(
      _entities[0].properties[7]);

  /// See [KanjiProgressEntity.lastSeenMs].
  static final lastSeenMs = obx.QueryIntegerProperty<KanjiProgressEntity>(
      _entities[0].properties[8]);
}
